# Run `tox -e update-pre-commit` to update the hook versions.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 3b3f7c3f57fe9925356faf5fe6230835138be230  # frozen: v0.15.17
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4  # frozen: v3.21.2
    hooks:
      - id: pyupgrade
        name: "Enforce Python 3.10+ idioms"
        args: ["--py310-plus"]
